# .github/actions/wrap-action/action.yml
name: "Wrap private docker action"
description: Wrap private docker action

runs:
  using: "composite"
  steps:
    - uses: docker/login-action@v3
      with:
        username: ${{ secrets.docker_username }}
        password: ${{ secrets.docker_password }}
    - name: Run private-image action
      uses: ./actions/private-docker-action
