# .github/actions/wrap-action/action.yml
name: "Wrap private docker action"
description: Wrap private docker action

runs:
  using: "composite"
  steps:
    - uses: docker/login-action@v3
      with:
        username: 631043
        password: dckr_pat_zOps2iZ5oC0cIwAQTrmWV6w7WF8
    - name: Run private-image action
      uses: ./actions/private-docker-action
