name: Custom Github Action

on:
  push:
    branches:
      - main

jobs:
  build-oci-image-container-test:
    name: build-oci-image-container-test
    runs-on: ubuntu-latest

    env:
      TEST_TAG: localhost:5001/actions/hello-world-docker-action:latest
      username: vikram

    steps:

      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Passing the values to container
        uses: ./actions/wrap-action
        with:
          container_file_path: Containerfile
          hadolint_config: test-hadolint-config.yaml
          acr: true