name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-docker:
    name: Docker Tests
    runs-on: ubuntu-latest

    env:
      TEST_TAG: localhost:5001/actions/hello-world-docker-action:latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Build the Container
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: ${{ env.TEST_TAG }}

      - name: Print Output
        id: output
        run: echo "${{ env.inputs.who-to-greet }}"
